services:
  whoami:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.${APP_NAME}.entrypoints=web
      - traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}
    networks:
      - proxy
      - default

networks:
  proxy:
    external: true
